<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">';
echo '<meta name="description" content="">';
echo '<meta name="author" content="">';
echo '';
echo '<title>About and Quick Guide</title>';
echo '';
echo '<!-- Bootstrap core CSS -->';
echo '<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">';
echo '';
echo '<!-- Custom styles for this template -->';
echo '<link href="css/scrolling-nav.css" rel="stylesheet">';
echo '';
echo '</head>';
echo '';
echo '<body id="page-top">';
echo '';
echo '<!-- Navigation -->';
echo '<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">';
echo '<div class="container">';
echo '<a class="navbar-brand js-scroll-trigger" href="#page-top">About</a>';
echo '<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarResponsive">';
echo '<ul class="navbar-nav ml-auto">';
echo '<!--<li class="nav-item">';
echo '<a class="nav-link js-scroll-trigger" href="#about">About</a> -->';
echo '<li class="nav-item">';
echo '<a class="nav-link js-scroll-trigger" href="contactform.php">Contact</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '';
echo '<header class="bg-primary text-white">';
echo '<style>';
echo 'div {';
echo 'text-align: justify;';
echo 'text-justify: inter-word;';
echo '}';
echo '</style>';
echo '<div class="container text-center">';
echo '<h1>CDSP Student Organization Information and Voting System</h1>';
echo '<p class="lead">A landing page template freshly redesigned for Bootstrap 4</p>';
echo '</div>';
echo '</header>';
echo '';
echo '<section id="about">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-8 mx-auto">';
echo '<h2>About The System</h2>';
echo '<p class="lead"></p></p>';
echo 'Hello everyone! In behalf of Team Katagumpay, My Name is Marco from BSIT 1-42 of Colegio de San Pedro!';
echo 'As a Team Leader of this project, we are proudly to introduce to you our madely "CDSP Student Organization Information and Voting System".';
echo 'This voting system can help our co-students to view some basic information on an organization and to vote and also to the election admin can manage the';
echo 'election easily. <br><br> As an open-source project developed together with my helpful and hardworking teammates Andrei Leyva and Francis Yabes we are here to help';
echo 'you on how to use the system! <br> <br>';
echo '';
echo 'Features: <br><br>';
echo '-For Admin <br>';
echo '*Can Add by Importing or Manual Adding Voters and modify them <br>';
echo '*Can Add by Importing and Delete Candidate<br>';
echo '*Can monitor election status<br>';
echo '*Can print election data (Voters, Candidates, and Election Results)<br> <br>';
echo '';
echo '-For Voters <br>';
echo '*Can View Basic Organization Information <br>';
echo '*Can Vote <br><br>';
echo '';
echo '';
echo 'Note : <br>';
echo '-For admin, sending voter's credentials can be done by installing an add-on in microsoft excel <br>';
echo 'which is kutools add-on we will have a tutorial video on how to use the add-on, but still we are trying our best to integrate it on the system thru phpmailer. <br>';
echo '-For admin, the election tally can be refreshed manually by pressing "F5" button, however we are also still trying our best';
echo 'to make it automatically refreshed thru ajax. <br>';
echo '-For Voters, in case you forgot the password you can tell the election admin to revert it to default password. <br>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section id="services" class="bg-light">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-8 mx-auto">';
echo '<h2>Quick Guide Video</h2> <br>';
echo 'For Admin <br>';
echo '<!--insert embedded youtube video here-->';
echo 'For Voters <br>';
echo '<iframe width="420" height="315" src="https://www.youtube.com/embed/BpcJIuT9CcE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
echo '<br>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '<!-- Footer -->';
echo '<footer class="py-5 bg-dark">';
echo '<div class="container">';
echo '<p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>';
echo '</div>';
echo '<!-- /.container -->';
echo '</footer>';
echo '';
echo '<!-- Bootstrap core JavaScript -->';
echo '<script src="vendor/jquery/jquery.min.js"></script>';
echo '<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>';
echo '';
echo '<!-- Plugin JavaScript -->';
echo '<script src="vendor/jquery-easing/jquery.easing.min.js"></script>';
echo '';
echo '<!-- Custom JavaScript for this theme -->';
echo '<script src="js/scrolling-nav.js"></script>';
echo '';
echo '</body>';
echo '';
echo '</html>';
echo '';
?>