<?php
echo '<!DOCTYPE HTML>';
echo '<html>';
echo '<head>';
echo '<title>Choose Org</title>';
echo '<link rel="shortcut icon" type="image/png" href="assets/favicons/cdsp.png">';
echo '<meta charset="utf-8" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1" />';
echo '<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->';
echo '<link rel="stylesheet" href="kawa/assets/css/main.css" />';
echo '<link rel="icon" href="images/cdsp.png">';
echo '<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->';
echo '</head>';
echo '<body>';
echo '';
echo '<!-- Header -->';
echo '<section id="header">';
echo '<header>';
echo '<span class="image avatar"><img src="images/cdsp.png" alt="" /></span>';
echo '<h1>Choose an organization</h1>';
echo '</header>';
echo '<nav id="nav">';
echo '<ul>';
echo '<li><a href="#one" class="active">OPS</a></li>';
echo '<li><a href="#two">SSC</a></li>';
echo '<li><a href="#three">TEATRO BATINGAW</a></li>';
echo '</ul>';
echo '</nav>';
echo '';
echo '</footer>';
echo '</section>';
echo '';
echo '<!-- Wrapper -->';
echo '<div id="wrapper">';
echo '';
echo '<!-- Main -->';
echo '<div id="main">';
echo '';
echo '<!-- One -->';
echo '<section id="one">';
echo '<div class="container">';
echo '<header class="major">';
echo '<h2>CDSP OPS</h2>';
echo '';
echo '<p style="text-align:justify">One of the Student Orgs in CDSP for BSOA students  </br><a href="ops.php" target="_blank">View more...</a></p>';
echo '<								</div>';
echo '</section>';
echo '';
echo '<!-- Two -->';
echo '<section id="two">';
echo '<div class="container">';
echo '<h3>CDSP SSC (Supreme Student Council)</h3>';
echo '<p style="text-align:justify">The Student Council exists to represent the voice of the students, promote their ideas and advocate their views and interests. It is a fundamentally democratic and non-political institution, with all students given equal opportunity to participate. Its role includes helping the school to serve its students as effectively as possible and making students aware of wider issues, in addition to playing an important role in establishing links with the community.</br><a href="ssc_oa.php" target="_blank">View more...</a></p>';
echo '';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Three -->';
echo '<section id="three">';
echo '<div class="container">';
echo '<h3>Teatro Batingaw</h3>';
echo '<p>The Teatro Batingaw is responsible for perfomances in various school programs promoting the school particularly in theater arts. It takes charge of all college activities such as Foundation Week, Buwan ng Wika, and Christmas Celebration. </br><a href="teatro.php" target="_blank">View more...</a></p>';
echo '</div>';
echo '</section>';
echo '</div>';
echo '';
echo '<!-- Four -->';
echo '';
echo '';
echo '<!-- Footer -->';
echo '<section id="footer">';
echo '<div class="container">';
echo '<ul class="copyright">';
echo '<li>&copy; Test</li><li>Design: <a href="http://palusot.com" target="_blank">hello mictest</a></li>';
echo '</ul>';
echo '</div>';
echo '</section>';
echo '';
echo '</div>';
echo '';
echo '<!-- Scripts -->';
echo '<script src="assets/js/jquery.min.js"></script>';
echo '<script src="assets/js/jquery.scrollzer.min.js"></script>';
echo '<script src="assets/js/jquery.scrolly.min.js"></script>';
echo '<script src="assets/js/skel.min.js"></script>';
echo '<script src="assets/js/util.js"></script>';
echo '<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->';
echo '<script src="assets/js/main.js"></script>';
echo '';
echo '</body>';
echo '</html>';
?>